FROM ghcr.io/astral-sh/uv:latest AS builder

FROM ghcr.io/bizcodepub/base-debian-python3:0.2.0

LABEL author = "Zaheer Abzal"

COPY --from=builder /uv /usr/local/bin/uv
# Or, to pin to a specific version:
# COPY --from=ghcr.io/astral-sh/uv:0.7.0 /uv /usr/local/bin/uv
# Ensure uv is in the PATH
ENV PATH="/usr/local/bin/:$PATH"


RUN uv venv /opt/venv
# Use the virtual environment automatically
ENV VIRTUAL_ENV=/opt/venv
# Place entry points in the environment at the front of the path
ENV PATH="/opt/venv/bin:$PATH"


COPY requirements.txt /tmp

# Install packages globally into the site-packages
RUN uv pip install -r /tmp/requirements.txt

# Set up the environment to use installed packages
# ENV PATH="/opt/venv/bin:$PATH"

# # --break-system-packages flag allows packages to be installed globally without a Python virtual environment
# RUN pip install -r /tmp/requirements.txt --break-system-packages

