FROM ghcr.io/bizcodepub/base-debian-python3:0.2.0 AS base

LABEL author = "Zaheer Abzal"
LABEL version = "0.2.0"

COPY requirements.txt /tmp


RUN apt update && apt install -y --no-install-recommends \
    gcc=4:12.2.0-3 \
    build-essential=12.9 \
    python3-dev

# --break-system-packages flag allows packages to be installed globally without a Python virtual environment
RUN pip install -r /tmp/requirements.txt --break-system-packages

